### ISSUE TITLE
 404  Not Found

### ISSUE THREAD

**Issue by twixi** [dockette/php#14]
FROM dockette/debian:wheezy

> Ign http://deb.debian.org wheezy Release.gpg
Ign http://deb.debian.org wheezy-updates Release.gpg
Ign http://deb.debian.org wheezy Release
Ign http://deb.debian.org wheezy-updates Release
Ign http://security.debian.org wheezy/updates Release.gpg
Ign http://security.debian.org wheezy/updates Release
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://deb.debian.org wheezy/main amd64 Packages
  404  Not Found
Err http://security.debian.org wheezy/updates/main amd64 Packages
Err http://deb.debian.org wheezy-updates/main amd64 Packages
  404  Not Found
Err http://security.debian.org wheezy/updates/main amd64 Packages
  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://deb.debian.org/debian/dists/wheezy-updates/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://security.debian.org/debian-security/dists/wheezy/updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
>

**Comment by f3l1x** [comment]
Hi @twixi.

How about now? I've fixed wheezy deps using archive.debian.org.

https://hub.docker.com/layers/dockette/php/5.5/images/sha256-906119795aff8448765b39ec28ce6b51072097761858424d0fa19c242b7ee8f7

Let me know.

Ref: https://github.com/dockette/debian/commit/9d2f1cf8bd8ceb372eeb17036df8bd5c4e4fa0f0

**Comment by f3l1x** [comment]
Closing it now. Let me know.
