### ISSUE TITLE
php7.3-fpm manifest issue

### ISSUE THREAD

**Issue by luigimolinaro** [dockette/php#17]
I'm not able to pull  docker pull hp:7.3-fpm manigest

Step to reproduce

`#docker pull dockette/php:7.3-fpm
Error response from daemon: manifest for dockette/php:7.3-fpm not found: manifest unknown: manifest unknown
`

**Comment by f3l1x** [comment]
There is a tag on Docker Hub (https://hub.docker.com/repository/docker/dockette/php/tags?page=1&ordering=last_updated&name=7.3).

It's maybe issue on Docker Hub side?
