### ISSUE TITLE
Add more PHP (5.5, 7.1)

### ISSUE THREAD

**Issue by f3l1x** [dockette/php#2]
- [x] 5.5

**Comment by lsv** [comment]
* [x] 7.1
* [ ] nightly

**Comment by f3l1x** [comment]
@lsv Thanks. I'll work on that. Do you use `dockette/php`?

**Comment by lsv** [comment]
Nope, because 7.1 and nightly is not there :)

**Comment by f3l1x** [comment]
@lsv PHP 7.1 included

**Comment by f3l1x** [comment]
@lsv PHP 5.5 included

**Comment by f3l1x** [comment]
Nightly is not in my plan at this moment. :-)
