### ISSUE TITLE
Unable to bind listening socket

### ISSUE THREAD

**Issue by novjan** [dockette/php#3]
I try your example command `docker run -v /path/to/site:/srv dockette/php:7.1-fpm`, but I am getting:
ERROR: unable to bind listening socket for address '/run/php/php7.1-fpm.sock': No such file or directory

**Comment by f3l1x** [comment]
Hi. 

It's strange, I use it every day and it's oukey. Can you please send me the whole demo of yours?

**Comment by novjan** [comment]
I will try some investigation. But I am starting with docker, so my demo is only one index.php :)
Btw same problem was with docker-compose

**Comment by f3l1x** [comment]
@novjan You're right, it's a bug. I'll will fix it, thank you. :-)

**Comment by novjan** [comment]
@f3l1x Oh, THX. I will be waiting :)

**Comment by f3l1x** [comment]
Fixed via: 
- https://github.com/dockette/php/commit/96c4dc6418878cb19440e3d066f73dc52e3c0b92
- https://github.com/dockette/php/commit/21a178c36d29740e2cdd9d72ed6e382b1ac4d228
