### ISSUE TITLE
Missing git

### ISSUE THREAD

**Issue by novjan** [dockette/php#8]
Please can you add git? @f3l1x 
Now when I run composer i see errors like:
```
sh: 1: git: not found
Failed to download kdyby/translation from source: Failed to clone https://github.com/Kdyby/Translation.git, git was not found, check that it is installed and in your PATH env.
```

**Comment by f3l1x** [comment]
Well, these images are runtime-images. You shouldn't use git in these containers. What is your use-case?

**Comment by novjan** [comment]
Hi. Sorry that it takes so long. I forgot on it.
I have componser.json and I just run composer install.
And i have some packages in repositories section of composer. Becuase they are private and we are not using packagist for them.

**Comment by f3l1x** [comment]
Oh I get it now. Could you please prepare PR?

**Comment by f3l1x** [comment]
Added.
